//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduOne.Data.Fr
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationForms()
        {
            this.ApplicationFormsSecurity = new HashSet<ApplicationFormsSecurity>();
        }
    
        public System.Guid Id { get; set; }
        public string Form { get; set; }
        public string Description { get; set; }
        public System.DateTime AjouterAu { get; set; }
        public string AjouterPar { get; set; }
        public Nullable<System.DateTime> ModifierAu { get; set; }
        public string ModifierPar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationFormsSecurity> ApplicationFormsSecurity { get; set; }
    }
}
