//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduOne.Data.Fr
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFormsSecurity
    {
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid FormId { get; set; }
        public System.DateTime AjouterAu { get; set; }
        public string AjouterPar { get; set; }
        public Nullable<System.DateTime> ModifierAu { get; set; }
        public string ModifierPar { get; set; }
    
        public virtual ApplicationForms ApplicationForms { get; set; }
        public virtual ApplicationRoles ApplicationRoles { get; set; }
    }
}
