//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduOne.Data.Fr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EduOne_FrEntities : DbContext
    {
        public EduOne_FrEntities()
            : base("name=EduOne_FrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationForms> ApplicationForms { get; set; }
        public virtual DbSet<ApplicationFormsSecurity> ApplicationFormsSecurity { get; set; }
        public virtual DbSet<ApplicationRoles> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }
    }
}
