// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Eduone.Fr.Data.Entities;

[Index("Form", Name = "UQ__Applicat__386CF3FD7B48B19D", IsUnique = true)]
public partial class ApplicationForms
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(800)]
    public string Form { get; set; }

    [Required]
    [StringLength(200)]
    public string Description { get; set; }

    public DateTime AjouterAu { get; set; }

    [Required]
    [StringLength(80)]
    public string AjouterPar { get; set; }

    public DateTime? ModifierAu { get; set; }

    [StringLength(80)]
    public string ModifierPar { get; set; }

    [InverseProperty("Form")]
    public virtual ICollection<ApplicationFormsSecurity> ApplicationFormsSecurity { get; set; } = new List<ApplicationFormsSecurity>();
}