// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EduOne.Fr.Data.Helpers;
using Microsoft.EntityFrameworkCore;

namespace Eduone.Fr.Data.Entities;

public partial class EduOne_FrContext : DbContext
{
    public EduOne_FrContext()
    {
    }

    public EduOne_FrContext(DbContextOptions<EduOne_FrContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ApplicationForms> ApplicationForms { get; set; }

    public virtual DbSet<ApplicationFormsSecurity> ApplicationFormsSecurity { get; set; }

    public virtual DbSet<ApplicationRoles> ApplicationRoles { get; set; }

    public virtual DbSet<ApplicationSettings> ApplicationSettings { get; set; }

    public virtual DbSet<ApplicationUserExportPermissions> ApplicationUserExportPermissions { get; set; }

    public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }

    public virtual DbSet<Classrooms> Classrooms { get; set; }

    public virtual DbSet<Courses> Courses { get; set; }

    public virtual DbSet<DepartmentHeads> DepartmentHeads { get; set; }

    public virtual DbSet<Departments> Departments { get; set; }

    public virtual DbSet<Enrollments> Enrollments { get; set; }

    public virtual DbSet<Fees> Fees { get; set; }

    public virtual DbSet<FeesStatus> FeesStatus { get; set; }

    public virtual DbSet<SemesestersFees> SemesestersFees { get; set; }

    public virtual DbSet<Semesters> Semesters { get; set; }

    public virtual DbSet<StaffNotes> StaffNotes { get; set; }

    public virtual DbSet<StaffRoles> StaffRoles { get; set; }

    public virtual DbSet<Staffs> Staffs { get; set; }

    public virtual DbSet<StudentIdentifications> StudentIdentifications { get; set; }

    public virtual DbSet<Students> Students { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer(DbHelpers.CS);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApplicationForms>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3214EC076DBA7B48");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<ApplicationFormsSecurity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3214EC074FB3CAD3");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Form).WithMany(p => p.ApplicationFormsSecurity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__FormI__30F848ED");

            entity.HasOne(d => d.Role).WithMany(p => p.ApplicationFormsSecurity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__RoleI__300424B4");
        });

        modelBuilder.Entity<ApplicationRoles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3214EC077A5C8C51");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<ApplicationSettings>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__tmp_ms_x__3214EC272D5603F3");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.CanBeAltered).HasDefaultValue(true);
            entity.Property(e => e.Statut).HasDefaultValue(true);
        });

        modelBuilder.Entity<ApplicationUserExportPermissions>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Applicat__3214EC2731D1FA06");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
        });

        modelBuilder.Entity<ApplicationUsers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07A9D39E94");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Role).WithMany(p => p.ApplicationUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__RoleI__403A8C7D");
        });

        modelBuilder.Entity<Classrooms>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07624C2442");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.Statut).HasDefaultValue(true);
        });

        modelBuilder.Entity<Courses>(entity =>
        {
            entity.HasKey(e => e.Cours_Id).HasName("PK__tmp_ms_x__C79C8A3FF1E3849D");

            entity.Property(e => e.Statut).HasDefaultValue(true);

            entity.HasOne(d => d.ID_DepartmentNavigation).WithMany(p => p.Courses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Courses__ID_Depa__5EBF139D");
        });

        modelBuilder.Entity<DepartmentHeads>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07B0A0C16F");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.Statut).HasDefaultValue(true);
        });

        modelBuilder.Entity<Departments>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07596CF2F3");
        });

        modelBuilder.Entity<Enrollments>(entity =>
        {
            entity.HasKey(e => e.InscriptionID).HasName("PK__tmp_ms_x__3332B196816AB29C");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.Statut).HasDefaultValue(true);
        });

        modelBuilder.Entity<Fees>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__Fees__3214EC27C88B0364");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
        });

        modelBuilder.Entity<FeesStatus>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__FeesStat__3214EC270AA537F0");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
        });

        modelBuilder.Entity<SemesestersFees>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Semesest__3214EC075D12AA4B");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
        });

        modelBuilder.Entity<Semesters>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__tmp_ms_x__3214EC2755C6817B");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
            entity.Property(e => e.Année).HasDefaultValueSql("(datepart(year,getdate()))");
            entity.Property(e => e.Statut).HasDefaultValue(true);
        });

        modelBuilder.Entity<StaffNotes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StaffNot__3214EC073210925E");

            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
        });

        modelBuilder.Entity<StaffRoles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StaffRol__3214EC07E95D4614");
        });

        modelBuilder.Entity<Staffs>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC071E6A968B");

            entity.Property(e => e.Status).HasDefaultValue(true);
        });

        modelBuilder.Entity<StudentIdentifications>(entity =>
        {
            entity.HasKey(e => e.UID).HasName("PK__StudentI__C5B19602F22FFA6A");

            entity.Property(e => e.UID).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AjouterAu).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.AjouterPar).HasDefaultValueSql("(suser_sname())");
        });

        modelBuilder.Entity<Students>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC0701D96B9B");

            entity.Property(e => e.GlobalId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Statut).HasDefaultValue(true);
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}