// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Eduone.Fr.Data.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Eduone.Fr.Data.Entities
{
    public partial class EduOne_FrContext
    {
        private IEduOne_FrContextProcedures _procedures;

        public virtual IEduOne_FrContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new EduOne_FrContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IEduOne_FrContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class EduOne_FrContextProcedures : IEduOne_FrContextProcedures
    {
        private readonly EduOne_FrContext _context;

        public EduOne_FrContextProcedures(EduOne_FrContext context)
        {
            _context = context;
        }

        public virtual async Task<List<proc_rpt_get_all_usersResult>> proc_rpt_get_all_usersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<proc_rpt_get_all_usersResult>("EXEC @returnValue = [dbo].[proc_rpt_get_all_users]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<proc_rpt_get_department_headsResult>> proc_rpt_get_department_headsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<proc_rpt_get_department_headsResult>("EXEC @returnValue = [dbo].[proc_rpt_get_department_heads]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
