// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Eduone.Fr.Data.Entities;

namespace Eduone.Fr.Data.Entities
{
    public partial class EduOne_FrContext
    {

        [DbFunction("func_decrypt_password", "dbo")]
        public static string func_decrypt_password(string password, byte[] EncryptedValue)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_encrypt_password", "dbo")]
        public static byte[] func_encrypt_password(string password)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_get_department_head_name", "dbo")]
        public static string func_get_department_head_name(int? department_head_id, int? department_id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_get_french_date", "dbo")]
        public static string func_get_french_date(bool? as_today, DateTime? date)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_get_roleId", "dbo")]
        public static Guid? func_get_roleId(string role)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_validate_password", "dbo")]
        public static bool? func_validate_password(string email, string password)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
