// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Eduone.Fr.Data.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Eduone.Fr.Data.Entities
{
    public partial interface IEduOne_FrContextProcedures
    {
        Task<List<proc_rpt_get_all_usersResult>> proc_rpt_get_all_usersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<proc_rpt_get_department_headsResult>> proc_rpt_get_department_headsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
