// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Eduone.Fr.Data.Entities
{
    public partial class proc_rpt_get_all_usersResult
    {
        [StringLength(50)]
        public string Utilisateur { get; set; }
        [StringLength(9)]
        public string Password { get; set; }
        [StringLength(7)]
        public string Statut { get; set; }
        [StringLength(100)]
        public string Nom { get; set; }
        [StringLength(200)]
        public string Prénom { get; set; }
        [StringLength(200)]
        public string DateNaissance { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        public DateTime AjouterAu { get; set; }
        [StringLength(80)]
        public string AjouterPar { get; set; }
        public DateTime? ModifierAu { get; set; }
        [StringLength(80)]
        public string ModifierPar { get; set; }
    }
}
