// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Eduone.Fr.Data.Entities
{
    public partial class proc_rpt_get_department_headsResult
    {
        [StringLength(200)]
        public string Nom { get; set; }
        [StringLength(200)]
        public string Prénom { get; set; }
        [StringLength(200)]
        public string DateNaissance { get; set; }
        [StringLength(25)]
        public string Téléphone { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        [StringLength(25)]
        public string Fax { get; set; }
        [StringLength(7)]
        public string Statut { get; set; }
        [StringLength(2147483647)]
        public string Notes { get; set; }
        public DateTime AjouterAu { get; set; }
        [StringLength(80)]
        public string AjouterPar { get; set; }
        public DateTime? ModifierAu { get; set; }
        [StringLength(80)]
        public string ModifierPar { get; set; }
    }
}
