// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Eduone.Fr.Data.Entities;

public partial class StudentIdentifications
{
    [Key]
    public Guid UID { get; set; }

    public int Id { get; set; }

    [StringLength(255)]
    public string FileName { get; set; }

    [StringLength(100)]
    public string ContentType { get; set; }

    public byte[] FileData { get; set; }

    public DateTime AjouterAu { get; set; }

    [Required]
    [StringLength(80)]
    public string AjouterPar { get; set; }

    public DateTime? ModifierAu { get; set; }

    [StringLength(80)]
    public string ModifierPar { get; set; }
}