// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduOne.Fr.RestServices.Entities;

public partial class ApplicationFormsSecurity
{
    [Key]
    public Guid Id { get; set; }

    public Guid RoleId { get; set; }

    public Guid FormId { get; set; }

    public DateTime AjouterAu { get; set; }

    [Required]
    [StringLength(80)]
    public string AjouterPar { get; set; }

    public DateTime? ModifierAu { get; set; }

    [StringLength(80)]
    public string ModifierPar { get; set; }

    [ForeignKey("FormId")]
    [InverseProperty("ApplicationFormsSecurity")]
    public virtual ApplicationForms Form { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("ApplicationFormsSecurity")]
    public virtual ApplicationRoles Role { get; set; }
}