// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EduOne.Fr.RestServices.Entities;

[Index("NomRole", Name = "UQ__Applicat__ADB14FA697F4B30C", IsUnique = true)]
public partial class ApplicationRoles
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string NomRole { get; set; }

    [Required]
    [StringLength(200)]
    public string Description { get; set; }

    public DateTime AjouterAu { get; set; }

    [Required]
    [StringLength(80)]
    public string AjouterPar { get; set; }

    public DateTime? ModifierAu { get; set; }

    [StringLength(80)]
    public string ModifierPar { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<ApplicationFormsSecurity> ApplicationFormsSecurity { get; set; } = new List<ApplicationFormsSecurity>();

    [InverseProperty("Role")]
    public virtual ICollection<ApplicationUsers> ApplicationUsers { get; set; } = new List<ApplicationUsers>();
}