// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EduOne.Fr.RestServices.Entities;

public partial class EduOne_FrContext : DbContext
{
    public EduOne_FrContext()
    {
    }

    public EduOne_FrContext(DbContextOptions<EduOne_FrContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ApplicationForms> ApplicationForms { get; set; }

    public virtual DbSet<ApplicationFormsSecurity> ApplicationFormsSecurity { get; set; }

    public virtual DbSet<ApplicationRoles> ApplicationRoles { get; set; }

    public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }

    public virtual DbSet<Courses> Courses { get; set; }

    public virtual DbSet<Departments> Departments { get; set; }

    public virtual DbSet<StaffRoles> StaffRoles { get; set; }

    public virtual DbSet<Staffs> Staffs { get; set; }

    public virtual DbSet<Students> Students { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(DbHelpers.CS);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApplicationForms>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3214EC076DBA7B48");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<ApplicationFormsSecurity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3214EC074FB3CAD3");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Form).WithMany(p => p.ApplicationFormsSecurity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__FormI__30F848ED");

            entity.HasOne(d => d.Role).WithMany(p => p.ApplicationFormsSecurity)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__RoleI__300424B4");
        });

        modelBuilder.Entity<ApplicationRoles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Applicat__3214EC077A5C8C51");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<ApplicationUsers>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07A9D39E94");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Role).WithMany(p => p.ApplicationUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Applicati__RoleI__403A8C7D");
        });

        modelBuilder.Entity<Courses>(entity =>
        {
            entity.HasKey(e => e.Cours_Id).HasName("PK__tmp_ms_x__C79C8A3FF1E3849D");

            entity.Property(e => e.Statut).HasDefaultValue(true);

            entity.HasOne(d => d.ID_DepartmentNavigation).WithMany(p => p.Courses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Courses__ID_Depa__5BE2A6F2");
        });

        modelBuilder.Entity<Departments>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC07B8F60382");
        });

        modelBuilder.Entity<StaffRoles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StaffRol__3214EC07E95D4614");
        });

        modelBuilder.Entity<Staffs>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Staffs__3214EC070297356B");
        });

        modelBuilder.Entity<Students>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Students__3214EC07D99C9738");

            entity.Property(e => e.GlobalId).HasDefaultValueSql("(newid())");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}