// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using EduOne.Fr.RestServices.Entities;

namespace EduOne.Fr.RestServices.Entities
{
    public partial class EduOne_FrContext
    {

        [DbFunction("func_decrypt_password", "dbo")]
        public static string func_decrypt_password(string password, byte[] EncryptedValue)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("func_encrypt_password", "dbo")]
        public static byte[] func_encrypt_password(string password)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
